### ISSUE TITLE
Error running mini test on "anvi-import-collection"

### ISSUE THREAD

**Issue by tedflynn** [meren/anvio#190]
Hi Meren,
I'm working on getting the pipeline set up in OS X 10.10.4, and was seemingly able to successfully install all of the necessary components. I started running the mini-test, it was cranking along happily until it errored out with:

~~~ bash
# Importing external binning results for splits into the profile database as 'SPLITS_IMPORTED'
#
#

usage: anvi-import-collection [-h] [-p PROFILE_DB] [-S SOURCE]
                              [--colors COLORS]
                              TAB DELIMITED FILE
anvi-import-collection: error: unrecognized arguments: -a test-output/ANNOTATION.db
~~~

Please let me know if this makes sense and I can provide any more details or input files that you need. 

Best,

Ted

**Comment by meren** [comment]
Dear Ted,

I am sorry about the confusion. This problem arises when the installed version of anvi'o is behind the mini_test.

For instance, this happens if you install the stable version through pip, and create a copy of the repo with git. 

For the latest test to run, the output should be identical to this (which shows the current -unstable- repository):

~~~ bash
$ anvi-refine -v
Anvi'o version ...............................: 1.0.2
Annotation DB version ........................: 3
Profile DB version ...........................: 5
~~~

I will think of a better solution for this before v1.1.0.

What is your current version?

**Comment by tedflynn** [comment]
No worries! That's exactly what I did (installed the stable version using pip, then copied the repository on git):

Anvi'o version ...............................: 1.0.1
Annotation DB version ........................: 3
Profile DB version ...........................: 5

So at this point the way forward to run the test would be to upgrade to the unstable version using git?

**Comment by meren** [comment]
You can also do this in anvi'o code directory:

~~~ bash
git checkout tags/v1.0.1
~~~

Then you should be able to run the mini_test (I hope).

**Comment by tedflynn** [comment]
Yep! Mini test was successfully run with no problems. I upgraded to the unstable version using the instructions on the installation page. Thanks for the help, Meren! I look forward to working with Anvi'o. It looks great so far!

**Comment by meren** [comment]
Great news. Thanks! I hope anvi'o would prove itself to be useful.
