### ISSUE TITLE
Better terminology for "metadata" instances in the code, and in command line clients

### ISSUE THREAD

**Issue by meren** [meren/anvio#194]
We have been calling a lot of things "metadata" throughout the development of anvi'o, when we should not have.

I already was upset about this situation (although failed, I attempted to fix it before too, i.e., #65). Finally when Susan Holmes (@spholmes) said "there is no such thing as metadata" during her last talk at the MBL, I decided to do something more concrete about this. Yes, everything is data, after all, and there should be better descriptions of what kind of data they are in the code than just calling things 'metadata' whenever it becomes challenging to find appropriate names.

I am going to start changing variable names and parameters that are called "metadata" into things such as "view data", "layer data", "additional view data", and such. This will stir things up in the codebase, previously-used parameters will be missing from command line clients, tests will fail, and our currently-quite-tiny user base will be upset because their batch scripts will not work. I will try to keep the damage to a minimum, and document everything. I am sorry for any inconvenience in advance, and I apologize for not doing a better job earlier.

**Comment by spholmes** [comment]
Of course I agree and the tack we took with phyloseq is to
organize things as
sample_data (any data, times samples were taken, clinical covariates
etc.....that qualify samples)
tax_table has all the data about the taxa and we are extending phyloseq to
include many other `kinds of data'.

Thanks for listening...

On Sun, Aug 23, 2015 at 9:07 AM, A. Murat Eren <notifications@github.com>
wrote:

> We have been calling a lot of things "metadata" throughout the development
> of anvi'o, when we should not.
>
> I already was upset about this situation (although failed, I attempted to
> fix it before too, i.e., #65 <https://github.com/meren/anvio/issues/65>).
> When Susan Holmes (@spholmes <https://github.com/spholmes>) said "there
> is no such thing as metadata" during her last talk at the MBL, I decided to
> do something more concrete about this. Yes, everything is data, after all,
> and there should be better descriptions of what kind of data they are in
> the code than just calling things 'metadata' whenever it becomes
> challenging to find appropriate names.
>
> I am going to start changing variable names and parameters that are called
> "metadata" into things such as "view data", "layer data", "additional view
> data", and such. This will stir things up in the codebase, previously-used
> parameters will be missing from command line clients, tests will fail, and
> our currently-quite-tiny user base will be upset because their batch
> scripts will not work. I will try to keep the damage to a minimum, and
> document everything. I am sorry for any inconvenience in advance, and I
> apologize for not doing a better job earlier.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/meren/anvio/issues/194>.
>



-- 
Susan Holmes
Professor, Statistics and BioX
John Henry Fellow in Undergraduate Education
Sequoia Hall,
390 Serra Mall
Stanford, CA 94305
http://www-stat.stanford.edu/~susan/

**Comment by amaralzettler** [comment]
Hellos,

I suggest contextual data ­ this is what we started calling it in the GSC
(Genomics Standards Consortium).

Linda

From:  "A. Murat Eren" <notifications@github.com>
Reply-To:  meren/anvio
<reply+00c4d5f1bcf4a3208df3993d62529481f895276608f4ed3292cf0000000111f1b1db9
2a169ce061e144f@reply.github.com>
Date:  Sunday, August 23, 2015 at 12:07 PM
To:  meren/anvio <anvio@noreply.github.com>
Subject:  [anvio] Better terminology for "metadata" instances in the code,
and in command line clients (#194)


We have been calling a lot of things "metadata" throughout the development
of anvi'o, when we should not.

I already was upset about this situation (although failed, I attempted to
fix it before too, i.e., #65 <https://github.com/meren/anvio/issues/65> ).
When Susan Holmes (@spholmes <https://github.com/spholmes> ) said "there is
no such thing as metadata" during her last talk at the MBL, I decided to do
something more concrete about this. Yes, everything is data, after all, and
there should be better descriptions of what kind of data they are in the
code than just calling things 'metadata' whenever it becomes challenging to
find appropriate names.

I am going to start changing variable names and parameters that are called
"metadata" into things such as "view data", "layer data", "additional view
data", and such. This will stir things up in the codebase, previously-used
parameters will be missing from command line clients, tests will fail, and
our currently-quite-tiny user base will be upset because their batch scripts
will not work. I will try to keep the damage to a minimum, and document
everything. I am sorry for any inconvenience in advance, and I apologize for
not doing a better job earlier.


Reply to this email directly or view it on GitHub
<https://github.com/meren/anvio/issues/194> .

**Comment by meren** [comment]
This is done!

~~~ bash
$ grep metadata * -nr | grep -v lib | grep -v svg
sandbox/anvi-script-upgrade-profile-db-v5-to-v6:37:        profile_db._exec('ALTER TABLE metadata_contigs RENAME TO atomic_data_contigs;')
sandbox/anvi-script-upgrade-profile-db-v5-to-v6:38:        profile_db._exec('ALTER TABLE metadata_splits RENAME TO atomic_data_splits;')
~~~

There is no instance of the word "metadata" in our codebase anymore.
