### ISSUE TITLE
HMMER3.1b2 is required to run the mini-test

### ISSUE THREAD

**Issue by jnesme** [meren/anvio#197]
When trying to run the mini test run after a fresh install via pip, I ran into an error at the "Populating search tables in the latest annotation database using default HMM profiles" step. This was due to hmmpress unable to process a temporary hmm.txt file, as shown in the log below. This issue can be circumvented by updating to HMMER3.1b2. After updating from HMMER3.1b1 to 3.1b2, hmmpress step worked ok and I could run entirely the mini test.

Sincerely, 

``` bash
CMD: hmmpress "/var/folders/l8/tqf0cz0n78zcpggqdhzn7_r80000gn/T/tmp9dOWBh/hmm.txt" >> "/var/folders/l8/tqf0cz0n78zcpggqdhzn7_r80000gn/T/tmp9dOWBh/00_log.txt" 2>&1

Error: File /var/folders/l8/tqf0cz0n78zcpggqdhzn7_r80000gn/T/tmp9dOWBh/hmm.txt does not appear to be in a recognized HMM format.

CMD: hmmscan -o "/var/folders/l8/tqf0cz0n78zcpggqdhzn7_r80000gn/T/tmp9dOWBh/hmm.output" --cut_ga --tblout "/var/folders/l8/tqf0cz0n78zcpggqdhzn7_r80000gn/T/tmp9dOWBh/hmm.hits.shitty" "/var/folders/l8/tqf0cz0n78zcpggqdhzn7_r80000gn/T/tmp9dOWBh/hmm.txt" "/var/folders/l8/tqf0cz0n78zcpggqdhzn7_r80000gn/T/tmp7HRAYv/contigs.proteins" >> "/var/folders/l8/tqf0cz0n78zcpggqdhzn7_r80000gn/T/tmp9dOWBh/00_log.txt" 2>&1

Error: Unrecognized format, trying to open hmm file /var/folders/l8/tqf0cz0n78zcpggqdhzn7_r80000gn/T/tmp9dOWBh/hmm.txt for reading.
```

**Comment by meren** [comment]
Dear Joseph,

Thank you very much for taking the time to report this.

The versioning of HMMER is not quite standard, so for now I decided not to attempt to check the version, but give a more reasonable error if things fail. When I downgrade my HMMER installation to 3.1b1 and run the test, it tells me this now instead of giving a cryptic error:

![image](https://cloud.githubusercontent.com/assets/197307/9567915/36da8868-4f09-11e5-9bc3-62098d3f1790.png)

This strategy is much less limiting, because instead of looking for a hard-coded version number, we are simply making sure the installed HMMER works well with all the HMM profiles it is given to work with. Two commits related to this report will follow.


Thanks again,
