### ISSUE TITLE
Installation error on Mac OSX

### ISSUE THREAD

**Issue by drjcthrash** [meren/anvio#207]
Hello,
I looked for my problem in both the open and closed issues, but didn't find it. Apologies if I simply missed it. I have installed all the dependencies, but when running

```
$ sudo pip install anvio
```

it errors out here:

```
running install_data
    creating /System/Library/Frameworks/Python.framework/Versions/2.7/ete2
     - Errors found! - 
    error: could not create '/System/Library/Frameworks/Python.framework/Versions/2.7/ete2': Operation not permitted
    
    ----------------------------------------
Command "/usr/bin/python -c "import setuptools, tokenize;__file__='/private/tmp/pip-build-WDQZTA/ete2/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-Gzd9L8-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /private/tmp/pip-build-WDQZTA/ete2
```

No further lines.

Any help would be much appreciated.

**Comment by meren** [comment]
Hi Cameron,

This is unfortunately about your Python installation. I usually suggest people who wish to have a working Python environment to get rid of their Python installation that comes with OSX, and install Python using [macports](https://www.macports.org/) (or [homebew](http://brew.sh/)). Because otherwise the life is very very hard with the default installation...

This is from another user tutorial, but if you wish to switch to macports based Python distribution, you can follow the first four steps here:

http://merenlab.org/2014/08/16/installing-the-oligotyping-pipeline/#installing-the-latest-stable-version-using-pip-suggested-method

It is fine, too, if you would like to continue using what Python system you have. However, I am looking at the error you sent, and I am having hard time making sense of it. It is most likely the directory pip is looking for is not there. Can you type this command to make sure whether it gives a directory not found error:

    ls /System/Library/Frameworks/Python.framework/Versions/2.7/

Thanks,

**Comment by drjcthrash** [comment]
Hi Murat,
Thanks for the quick response. Indeed, it would be better if I didn’t have to uninstall and re-install python, but if that’s what it takes, I can do that.

In response to your query about the directory, no there is no error running ls:

$ ls /System/Library/Frameworks/Python.framework/Versions/2.7/
Extras		Headers		Mac		Python		Resources	_CodeSignature	bin		include		lib

Does that help? If not, any tips on uninstalling the current Python build?

-jct

**Comment by meren** [comment]
Interesting. It is confusing. There are similar complaints online for the same type of error, and as far as I can see there is no clear answer to solve this.

I think re-installing Python using macports is going to be the cleanest solution. Nothing will change, all previous applications using Python will continue to work.

Please let me know if you run into any other issues.

**Comment by drjcthrash** [comment]
Ok thanks. Does it matter what version of python?

-jct

**Comment by meren** [comment]
Yes, it does. It needs to be 2.7.*, which is what your current Python version, so the change will be seamless.

If you follow the first four steps in this article, you will be golden :)

http://merenlab.org/2014/08/16/installing-the-oligotyping-pipeline/#installing-the-latest-stable-version-using-pip-suggested-method

**Comment by drjcthrash** [comment]
Roger that. Thank you!

Oh, and this is hilarious:

"This will install Python 2.7 on your system. I know that you already have Python installed, but you don’t want to use that one.”

-jct

**Comment by meren** [comment]
:)

Thank you for trying anvi'o. I would be very happy if you let me know when/if it works after this little adventure.

**Comment by drjcthrash** [comment]
My pleasure. I’ll keep you updated.

-jct

**Comment by meren** [comment]
I am closing this as I learned that this is resolved by installing Python through macports.

**Comment by drjcthrash** [comment]
But I did install Python through macports, just as you instructed.

-jct
