### ISSUE TITLE
Default order of layers in samples information section

### ISSUE THREAD

**Issue by meren** [meren/anvio#224]
The default order should be identical to the order of those layers in the input metadata file used to generate the samples database.

**Comment by meren** [comment]
I am working on this :)

**Comment by ozcanesen** [comment]
Meren i think we should pass layer order to buildSamplesTable function as if they are coming from the state, otherwise it will be overwritten. (categoricals first, then numericals etc.)
<img width="507" alt="screen shot 2015-11-14 at 2 18 17 pm" src="https://cloud.githubusercontent.com/assets/940884/11163470/9725c7e8-8ada-11e5-810c-5a895571a5f4.png">

**Comment by meren** [comment]
Thank you very much for noticing and fixing this :)

I was trying to do it without bothering you. Well, I tried. I expect at least a "B" for effort.
