### ISSUE TITLE
New coverage normalization (mean_coverage_Q1Q3)

### ISSUE THREAD

**Issue by meren** [meren/anvio#308]
To maintain the impact of extreme coverage values as much as possible (especially the zero values we observe in scaffolds that combine multiple pieces of DNA), and to obtain a more stable signal from contigs for clustering purposes, we need a normalized coverage option.

Using the mean value of coverage values that fall into the interquartile region (second, and third quartiles) of the coverage values of each contig could be useful to achieve that.

Here I will list changes in the master repository that facilitates this.

**Comment by tdelmont** [comment]
Hi,
if you do that, would be great to use this score early one for clustering contigs during merging. Should improve the binning experience!
Tom

**Comment by meren** [comment]
Yes. It is in the repo now. We need to test this for Infant data.

Plus, I am planning to use a similar principle to mark potentially bad SNV reports during profiling.

**Comment by tdelmont** [comment]
Ok, I have some nice examples using Ameet water metagenome (commamox bin):
Split example 1:
![screen shot 2016-01-30 at 1 46 33 pm](https://cloud.githubusercontent.com/assets/8332889/12698034/fd76d2bc-c757-11e5-8b46-4e15fcd4a18a.png)
Split example 2:
![screen shot 2016-01-30 at 1 46 51 pm](https://cloud.githubusercontent.com/assets/8332889/12698040/1a1f2626-c758-11e5-8c83-877d805a3100.png)


As you can see, in some cases coverage is ok in one sample but not in the other samples. The problem is that SNVs are clearly problematic in all samples. So we might want to remove positions for SNV analysis, instead of just SNVs within a sample due to inconsistent coverage. Makes sense?

**Comment by tdelmont** [comment]
Here is the current view of the commamox:
![screen shot 2016-01-30 at 1 51 08 pm](https://cloud.githubusercontent.com/assets/8332889/12698068/a59eaa00-c758-11e5-8ef8-31ce45dab2a1.png)
I can re-do the analysis with the new algorithm, and show how coverage becomes more stable across splits, using an important genome as a proof of principle. Tom
