### ISSUE TITLE
using color codes to automatically set colors for matrix tables in the interface

### ISSUE THREAD

**Issue by tdelmont** [meren/anvio#352]
Hi,
for some projects, it would be very useful to color layer values using a set of predefined colors.
For example #FF0000 for red.

So if a table to load is filled with color codes they could be automatically used in the interface.
This way we do not have to manually change the colors layers by layers (can easily become a pain)
Would this be possible???

thanks

tom

**Comment by meren** [comment]
I don't see how this could be done without destroying the design.

We have data structures to display stuff, and cosmetics are taken care of by state files. We can't put cosmetics into data files.

I think this is "wontfix" or "invalid", but I will let @ozcanesen have the pleasure since he is the assignee ;)

**Comment by ozcanesen** [comment]
I agree to @meren, We can already change layer colors programmatically using state files, However maybe we should develop a script that converts state json file to csv and vice versa, that way user can edit them in spreadsheet easily.

**Comment by meren** [comment]
Yes, we don't have an export/import function for states. It would have been very useful for large scale automated operations.
