### ISSUE TITLE
wrong coloring of some splits as "none" in the interface, with problems in the summary too

### ISSUE THREAD

**Issue by tdelmont** [meren/anvio#361]
Hi,
this is a reminding to a now old bug: some, but not all splits with no taxonomical affiliation are associated to a group called "none". It puts confusing coloring in the interface, and also as consequences in the summary html.

![screen shot 2016-05-06 at 2 25 52 pm](https://cloud.githubusercontent.com/assets/8332889/15084079/cdb23900-1396-11e6-8e92-f3a70254b67c.png)

**Comment by meren** [comment]
I'm passing it to @ozcanesen :)

**Comment by ozcanesen** [comment]
Hi Tom,
Can you send me the data set? Can i reproduce this on minitest?

**Comment by tdelmont** [comment]
the data is too big, but yes it is reproducible with mini test:

(PS: I am on 2.0.0)

![screen shot 2016-05-06 at 3 10 05 pm](https://cloud.githubusercontent.com/assets/8332889/15084965/b5da93ee-139c-11e6-8c53-4c3eb45980f5.png)

**Comment by ozcanesen** [comment]
I have fixed the issue in the interface, But @meren I think this may also affect other parts of the the pipeline, because empty taxonomy values in the contigs.db are not uniform.

```select t_species, count(*) from splits_taxonomy group by t_species;```

This query will show the result below:

<img width="260" alt="screen shot 2016-05-07 at 1 13 33 am" src="https://cloud.githubusercontent.com/assets/940884/15088059/c2036f46-13f7-11e6-93a1-a7a4952e434a.png">

I think these "None" values should NULL too, or we can set "None" as the default value of the t_species column

**Comment by meren** [comment]
Thanks a lot, @ozcanesen! Clearly I screwed up something as usual. I will look into the import script.

**Comment by meren** [comment]
Latest commits have fixed this issue.
